dia = input('Dia = ')
mês = input('Mês = ')
ano = input('Ano = ')
# print('Você nasceu no dia ', dia, ' de ', mês, ' do ano de', ano, '.')   
print(f'Você nasceu no dia {dia} de {mês} do ano de {ano}.')  