nome = input(str('Qual o seu nome? '))
idade = input('Quantos anos você tem? ')
unidade = input(str('Qual a sua unidade? '))
#print('Olá', nome, 'você tem', idade, 'anos', 'e estuda/trabalha na unidade', unidade)
#print('Olá, {}! Você tem {} anos e estuda na {}!'.format(nome, idade, unidade))
print(f'Olá, {nome}! Você tem {idade} anos e estuda na unidade {unidade}!')
